baseURL:
languageCode: en-us
title: Pitchdeck
disableKinds:
  - taxonomy
  - taxonomyTerm
enableRobotsTXT: true
params:
  description: >-
    Description
  twitter_user: kris_ray
  twitter_link: https://twitter.com/
  facebook_link: http://www.facebook.com/
  instagram_link: https://www.instagram.com/
  #google_analytics: UA-
  paid_for: Paid for By Here
